name: felix_practise_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.8.0
  retrofit: ^4.0.3
  dartz: ^0.10.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.8
  dio: ^5.4.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

 
  assets:
    - assets/icons/
    - assets/images/
    - lib/core/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
